[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bioshield"
version = "1.0.0"
description = "BioShield Soil Monitoring System"
authors = [
    {name = "Samir Baladi", email = "emerladcompass@gmail.com"}
]
license = {text = "MIT"}
