apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bioshield-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: bioshield.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bioshield-service
            port:
              number: 80
