apiVersion: v1
kind: Service
metadata:
  name: bioshield-service
  labels:
    app: bioshield
spec:
  selector:
    app: bioshield
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  type: ClusterIP
